'use server';
import prismadb from '@/lib/prismadb';
import { TGeneratorValidator } from '@/lib/validators/generator-validator';
import crypto from 'crypto';

export async function generateToken(data: TGeneratorValidator) {
  const { name, tickets } = data;
  const token = crypto.randomUUID();
  const user = await prismadb.user.create({
    data: { name, tickets, token },
  });
  console.log('token generated by server action');
  return user;
}
